name: Hello GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  prueba:
    name: Imprimir mensaje

    run-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: imprime con echo
      run : echo Hello, GH-Actions! 